[package]
name = "rusy-by-exmaple"
version = "0.1.0"
authors = ["Elton Zheng <elton.zheng.sh@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
